version: '3.8'

services:
  # WebApp Frontend
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000
      - NEXT_PUBLIC_TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - yovpn-network

  # WebApp API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - MARZBAN_API_URL=${MARZBAN_API_URL}
      - MARZBAN_USERNAME=${MARZBAN_USERNAME}
      - MARZBAN_PASSWORD=${MARZBAN_PASSWORD}
      - CORS_ORIGINS=http://webapp:3000,http://localhost:3000
    restart: unless-stopped
    networks:
      - yovpn-network

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
      - api
    restart: unless-stopped
    networks:
      - yovpn-network

networks:
  yovpn-network:
    driver: bridge
